#!/usr/bin/env python3
"""
Read criterion's per-bench JSON output (target/criterion/**/estimates.json)
and emit BENCHMARKS.md with one table per kernel comparing the rust and cxx
implementations head-to-head.

Run after `cargo bench --features bench-cxx --bench kernels`.

This script intentionally has no dependencies beyond the stdlib so it
runs cleanly under the rawkward-py312 conda env or any system python ≥ 3.8.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Iterable


def find_repo_root(start: Path) -> Path:
    p = start.resolve()
    for cand in [p, *p.parents]:
        if (cand / "Cargo.toml").is_file():
            return cand
    raise SystemExit(f"could not locate Cargo.toml above {start}")


def fmt_ns(ns: float) -> str:
    if ns < 1_000:
        return f"{ns:7.1f} ns"
    if ns < 1_000_000:
        return f"{ns / 1_000:7.2f} µs"
    if ns < 1_000_000_000:
        return f"{ns / 1_000_000:7.2f} ms"
    return f"{ns / 1_000_000_000:7.2f} s"


def fmt_ratio(rust_ns: float, cxx_ns: float) -> str:
    """Cxx baseline = 1.00x. Rust faster → < 1.00x; slower → > 1.00x."""
    if cxx_ns <= 0:
        return "—"
    r = rust_ns / cxx_ns
    arrow = "✓" if r <= 1.05 else ("≈" if r <= 1.20 else "✗")
    return f"{r:.2f}x {arrow}"


def collect_estimates(criterion_dir: Path) -> dict[tuple[str, str, str], float]:
    """
    Returns {(group_id, function_id, value_id): mean_ns}.

    Criterion's directory layout is:
      target/criterion/<group_id>/<function_id>/<value_id>/new/estimates.json
    """
    out: dict[tuple[str, str, str], float] = {}
    if not criterion_dir.is_dir():
        return out
    for est_path in criterion_dir.rglob("new/estimates.json"):
        # path:  …/criterion/<group>/<function>/<value>/new/estimates.json
        parts = est_path.relative_to(criterion_dir).parts
        if len(parts) < 5 or parts[-2] != "new":
            continue
        group_id = parts[0]
        function_id = parts[1]
        value_id = parts[2]
        try:
            data = json.loads(est_path.read_text())
            mean_ns = float(data["mean"]["point_estimate"])
        except (KeyError, ValueError, json.JSONDecodeError):
            continue
        out[(group_id, function_id, value_id)] = mean_ns
    return out


def render(estimates: dict[tuple[str, str, str], float]) -> str:
    by_group: dict[str, dict[str, dict[str, float]]] = {}
    for (group, function, value), mean in estimates.items():
        by_group.setdefault(group, {}).setdefault(value, {})[function] = mean

    lines: list[str] = []
    lines.append("# Per-kernel benchmarks: rawkward (Rust) vs awkward (C++)")
    lines.append("")
    lines.append(
        "Generated by `scripts/bench_to_markdown.py` from "
        "`target/criterion/<group>/.../estimates.json`. Each row is the criterion "
        "mean over 100 samples. **Ratio** is Rust mean ÷ C++ mean — values "
        "**below 1.00×** mean Rust is faster."
    )
    lines.append("")
    lines.append(
        "Three input sizes per kernel: `(elements / output_groups)` chosen to "
        "exercise L1, L2, and L3+main memory respectively."
    )
    lines.append("")

    has_pairs = any(
        ("rust" in fns and "cxx" in fns)
        for sizes in by_group.values() for fns in sizes.values()
    )
    if not has_pairs:
        lines.append("> ⚠ The C++ side wasn't included in this run. Re-run with")
        lines.append(">")
        lines.append("> ```")
        lines.append("> AWKWARD_CPP_PATH=~/Projects/awkward.2.9.x/awkward/awkward-cpp \\")
        lines.append(">     cargo bench --no-default-features --features bench-cxx --bench kernels")
        lines.append("> ```")
        lines.append("")

    summary_rows: list[tuple[str, float]] = []

    for group in sorted(by_group):
        sizes = by_group[group]
        lines.append(f"## `{group}`")
        lines.append("")
        lines.append("| input | Rust | C++ | ratio (Rust/C++) |")
        lines.append("|---|---|---|---|")
        ratios: list[float] = []
        for value in sorted(sizes, key=_natural_key):
            fns = sizes[value]
            rust = fns.get("rust")
            cxx = fns.get("cxx")
            rust_str = fmt_ns(rust) if rust is not None else "—"
            cxx_str = fmt_ns(cxx) if cxx is not None else "—"
            if rust is not None and cxx is not None and cxx > 0:
                ratio_str = fmt_ratio(rust, cxx)
                ratios.append(rust / cxx)
            else:
                ratio_str = "—"
            lines.append(f"| `{value}` | {rust_str} | {cxx_str} | {ratio_str} |")
        if ratios:
            geo = _geomean(ratios)
            summary_rows.append((group, geo))
        lines.append("")

    if summary_rows:
        lines.append("## Summary")
        lines.append("")
        lines.append("Geometric mean of (Rust / C++) across the three input sizes:")
        lines.append("")
        lines.append("| kernel | mean ratio |")
        lines.append("|---|---|")
        for group, geo in sorted(summary_rows, key=lambda x: x[1]):
            arrow = "✓" if geo <= 1.05 else ("≈" if geo <= 1.20 else "✗")
            lines.append(f"| `{group}` | {geo:.2f}x {arrow} |")
        lines.append("")
        overall = _geomean([r for _, r in summary_rows])
        lines.append(
            f"**Overall geomean ratio: {overall:.2f}× across {len(summary_rows)} kernels.**"
        )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("**Legend** — `✓` Rust within 5% of C++ or faster, "
                 "`≈` within 20%, `✗` 20%+ slower than C++.")
    lines.append("")
    return "\n".join(lines)


def _natural_key(s: str) -> tuple:
    """Sort `1024/128`, `65536/4096`, `1048576/16384` numerically."""
    out: list = []
    cur = ""
    for ch in s:
        if ch.isdigit():
            cur += ch
        else:
            if cur:
                out.append(int(cur))
                cur = ""
            out.append(ch)
    if cur:
        out.append(int(cur))
    return tuple(out)


def _geomean(xs: Iterable[float]) -> float:
    xs = [x for x in xs if x > 0]
    if not xs:
        return float("nan")
    log_sum = sum(__import__("math").log(x) for x in xs)
    return __import__("math").exp(log_sum / len(xs))


def main() -> int:
    repo = find_repo_root(Path(__file__).parent)
    criterion_dir = repo / "target" / "criterion"
    estimates = collect_estimates(criterion_dir)
    if not estimates:
        print(
            f"no criterion data found at {criterion_dir} — "
            "did you run `cargo bench --bench kernels`?",
            file=sys.stderr,
        )
        return 1
    md = render(estimates)
    out_path = repo / "BENCHMARKS.md"
    out_path.write_text(md)
    print(f"wrote {out_path} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
